name: Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to OpenShift
      run: |
        oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}

    - name: Build and Push Image
      run: |
        oc project <your-project>
        oc new-build --binary --name=python-mysql-app -l app=python-mysql-app
        oc start-build python-mysql-app --from-dir=. --follow

    - name: Install Helm and Deploy
      run: |
        helm install python-mysql-app charts/python-mysql-app --set image.repository=<your-registry>/python-mysql-app
